name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: docker build --target test --tag todo-app:test .
      - run: docker run --env-file .env -p 5000:5000 todo-app:test